# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('queries', models.TextField(max_length=700)),
                ('creation_time', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField()),
                ('payment_commission_charges', models.IntegerField()),
                ('form_category', models.CharField(max_length=10)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
