# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='request_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
