# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_response_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='class_join_option_sel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='request_id',
            field=models.CharField(max_length=16),
        ),
    ]
