# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_auto_20170810_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='cancel_policy',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='designation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='name_of_org_sel_internship',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='policy_getting_certificate',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='present_year_of_study',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='sel_japan_internship',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='taken_japanese_course',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='visited_japan',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
