# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_access_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_french',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('queries', models.TextField(max_length=700)),
                ('creation_time', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField()),
                ('payment_commission_charges', models.IntegerField()),
                ('form_category', models.CharField(max_length=10)),
                ('class_join_option_sel', models.CharField(max_length=100)),
                ('policy_getting_certificate', models.CharField(max_length=100)),
                ('cancel_policy', models.CharField(max_length=100)),
                ('sel_france_internship', models.CharField(max_length=100)),
                ('name_of_org_sel_internship', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('present_year_of_study', models.CharField(max_length=100)),
                ('taken_french_course', models.CharField(max_length=100)),
                ('visited_france', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
