# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_response_french'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response_french',
            name='class_join_option_sel',
        ),
        migrations.RemoveField(
            model_name='response_french',
            name='visited_france',
        ),
    ]
